version: '2'
services:
  es1:
    container_name: elasticsearch
    build: docker/elasticsearch/
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: tasker
      MYSQL_ROOT_PASSWORD: Penta20Couver!

  # es2:
  #   image: d.kt-team.de/elasticsearch:5.5.2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=es1"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 1g
  #   volumes:
  #     - ../../esdat2:/usr/share/elasticsearch/data

  #   networks:
  #     - esnet

  # kibana:
  #   image: kibana:5.5
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://es1:9200
  #   networks:
  #       - esnet

  redis:  
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  esdat1:
    driver: local
  esdat2:
    driver: local
